version: '3'
# This is example 3 from the documentation
services:
  meshcentral:
    container_name: meshcentral
    image: meshcentral-docker:latest
    build: .
    depends_on:
      - meshcentral-db 
    restart: "always"
    volumes:
      - ./container-data/meshcentral-data:/meshcentral/meshcentral-data
      - ./container-data/meshcentral-files:/meshcentral/meshcentral-files
      - ./container-data/meshcentral-backup:/meshcentral/meshcentral-backup
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MARIADB_HOST=meshcentral-db
      - MARIADB_PORT=3306
      - MARIADB_DATABASE=meshcentral
      - MARIADB_USER=${DBMESH_USER}
      - MARIADB_PASS=${DBMESH_PASS}
      - DB_ENCRYPT_KEY=${DB_ENCRYPT_KEY}
      - AGENT_PORT=8800
      - HOSTNAME=remoteit.local
    ports:
      - 8800:8800
      - 8081:80
      - 8443:443
    networks:
      - meshcentral-nw
#      - soporte_reverseproxy-nw
    
  meshcentral-db:
    container_name: meshcentral-db
    image: mariadb:10.7 #latest
    restart: "always"
    volumes:
      # - ./container-data/db:/data/db
      - mesh-data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_DATABASE=meshcentral
      - MYSQL_USER=${DBMESH_USER}
      - MYSQL_PASSWORD=${DBMESH_PASS}
      - MYSQL_ROOT_PASSWORD=${DBMESH_ROOT_PASS}
      - TZ=America/Lima 
    networks:
      - meshcentral-nw

volumes:
  mesh-data:

networks:
  meshcentral-nw:
#  soporte_reverseproxy-nw:
#    external: true
